// <auto-generated />
// Generated by varlock. Do not edit directly.

namespace Varlock.Generated
{
  public sealed partial class VarlockConfig
  {
    /// <summary>Original key: APP_ENV.</summary>
    /// <summary>Allowed values: dev, staging, prod.</summary>
    /// <summary>current application environment</summary>
    public string AppEnv { get; set; } = string.Empty;

    /// <summary>Original key: DB_HOST.</summary>
    /// <summary>database host name</summary>
    public string DbHost { get; set; } = string.Empty;

    /// <summary>Original key: DB_PORT.</summary>
    /// <summary>database port</summary>
    public int? DbPort { get; set; }

    /// <summary>Original key: DEBUG.</summary>
    /// <summary>enable debug output</summary>
    public bool? Debug { get; set; }

  }

  public static class VarlockConfigMetadata
  {
    public static global::System.Collections.Generic.IReadOnlyDictionary<string, string> PropertyKeys { get; } =
      new global::System.Collections.Generic.Dictionary<string, string>(global::System.StringComparer.Ordinal)
      {
        ["AppEnv"] = "APP_ENV",
        ["DbHost"] = "DB_HOST",
        ["DbPort"] = "DB_PORT",
        ["Debug"] = "DEBUG",
      };
  }
}