// <auto-generated />
// Generated by varlock. Do not edit directly.

namespace Varlock.Generated
{
  public sealed partial class VarlockConfig
  {
    /// <summary>Original key: APP_ENV.</summary>
    /// <summary>Allowed values: dev, staging, prod.</summary>
    /// <summary>current application environment</summary>
    public string AppEnv { get; set; } = string.Empty;

    /// <summary>Original key: DB_HOST.</summary>
    /// <summary>database host name</summary>
    public string DbHost { get; set; } = string.Empty;

    /// <summary>Original key: DB_PORT.</summary>
    /// <summary>database port</summary>
    public int? DbPort { get; set; }

    /// <summary>Original key: DEBUG.</summary>
    /// <summary>enable debug output</summary>
    public bool? Debug { get; set; }

    /// <summary>Original key: OPEN_AI_API_KEY.</summary>
    /// <summary>Sensitive.</summary>
    /// <summary>external API key</summary>
    public string OpenAiApiKey { get; set; } = string.Empty;

  }

  public static class VarlockConfigMetadata
  {
    public sealed class PropertyBinding
    {
      public PropertyBinding(string key, string propertyName, bool isRequired, bool isSensitive)
      {
        Key = key;
        PropertyName = propertyName;
        IsRequired = isRequired;
        IsSensitive = isSensitive;
      }

      public string Key { get; }

      public string PropertyName { get; }

      public bool IsRequired { get; }

      public bool IsSensitive { get; }
    }

    public static global::System.Collections.Generic.IReadOnlyList<PropertyBinding> PropertyBindings { get; } = new PropertyBinding[]
    {
      new PropertyBinding("APP_ENV", "AppEnv", true, false),
      new PropertyBinding("DB_HOST", "DbHost", true, false),
      new PropertyBinding("DB_PORT", "DbPort", false, false),
      new PropertyBinding("DEBUG", "Debug", false, false),
      new PropertyBinding("OPEN_AI_API_KEY", "OpenAiApiKey", true, true),
    };

    public static global::System.Collections.Generic.IReadOnlyDictionary<string, string> PropertyKeys { get; } =
      new global::System.Collections.Generic.Dictionary<string, string>(global::System.StringComparer.Ordinal)
      {
        ["AppEnv"] = "APP_ENV",
        ["DbHost"] = "DB_HOST",
        ["DbPort"] = "DB_PORT",
        ["Debug"] = "DEBUG",
        ["OpenAiApiKey"] = "OPEN_AI_API_KEY",
      };

    public static global::System.Collections.Generic.IReadOnlyList<string> SensitiveKeys { get; } = new string[]
    {
      "OPEN_AI_API_KEY",
    };
  }
}