import fs from 'node:fs';
import _ from '@env-spec/utils/my-dash';
import type { EnvGraph } from './env-graph';
import type { TypeGenItemInfo } from './config-item';


const AUTOGENERATED_FILE_BANNER = `
// 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑
// 🛑 THIS IS AN AUTOGENERATED FILE - DO NOT EDIT DIRECTLY 🛑
// 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑
`;

const AUTOGENERATED_CSHARP_FILE_BANNER = [
  '// <auto-generated />',
  '// Generated by varlock. Do not edit directly.',
].join('\n');

const CSHARP_RESERVED_WORDS = new Set([
  'Abstract',
  'As',
  'Base',
  'Bool',
  'Break',
  'Byte',
  'Case',
  'Catch',
  'Char',
  'Checked',
  'Class',
  'Const',
  'Continue',
  'Decimal',
  'Default',
  'Delegate',
  'Do',
  'Double',
  'Else',
  'Enum',
  'Event',
  'Explicit',
  'Extern',
  'False',
  'Finally',
  'Fixed',
  'Float',
  'For',
  'Foreach',
  'Goto',
  'If',
  'Implicit',
  'In',
  'Int',
  'Interface',
  'Internal',
  'Is',
  'Lock',
  'Long',
  'Namespace',
  'New',
  'Null',
  'Object',
  'Operator',
  'Out',
  'Override',
  'Params',
  'Private',
  'Protected',
  'Public',
  'Readonly',
  'Ref',
  'Return',
  'Sbyte',
  'Sealed',
  'Short',
  'Sizeof',
  'Stackalloc',
  'Static',
  'String',
  'Struct',
  'Switch',
  'This',
  'Throw',
  'True',
  'Try',
  'Typeof',
  'Uint',
  'Ulong',
  'Unchecked',
  'Unsafe',
  'Ushort',
  'Using',
  'Virtual',
  'Void',
  'Volatile',
  'While',
]);


const ICON_SIZE = 20;

let iconCacheFolderInit = false;
const iconInMemoryCache: Record<string, string> = {};

async function fetchIconSvg(
  iconifyName: string,
  color = '808080', // neutral gray that should appear on black or white bg
  iconCacheFolder = '/tmp/varlock-icon-cache', // TODO: maybe move icon cache to ~/.varlock dir?
) {
  // some notes about icons
  // - using a URL that points to an svg doesn't work (but png/jpg do work)
  // - but embedding data url with an svg works fine
  // - we are fetching them on demand and caching them
  // - and then applying a color if one is set or falling back to a neutral gray that should show up on either black or white

  if (!iconCacheFolderInit) {
    fs.mkdirSync(iconCacheFolder, { recursive: true });
    iconCacheFolderInit = true;
  }

  const iconPath = `${iconCacheFolder}/${iconifyName}-${ICON_SIZE}.svg`;

  let svgSrc: string | undefined;
  if (iconInMemoryCache[iconPath]) {
    svgSrc = iconInMemoryCache[iconPath];
  } else if (fs.existsSync(iconPath)) {
    const svgFileBuffer = await fs.promises.readFile(iconPath, 'utf-8');
    svgSrc = svgFileBuffer.toString();
    iconInMemoryCache[iconPath] = svgSrc;
  } else {
    try {
      const iconSvg = await fetch(`https://api.iconify.design/${iconifyName.replace(':', '/')}.svg?height=${ICON_SIZE}`);
      svgSrc = await iconSvg.text();
    } catch (err) {
      return;
    }
    if (!svgSrc) return;


    // TODO: optionally re-enable svgo - but only as a peer dependency?
    // // run it through svgo to try to shrink it down a little
    // const optimizedSvgResult = optimize(svgSrc, {
    //   multipass: true,
    // });
    // if (!optimizedSvgResult.data) throw new Error(`Failed to optimize SVG icon - ${iconifyName}`);
    // svgSrc = optimizedSvgResult.data as string;

    if (svgSrc) {
      await fs.promises.writeFile(iconPath, svgSrc, 'utf-8');
      iconInMemoryCache[iconPath] = svgSrc;
    }
  }


  const hexColor = color.startsWith('#') ? color : `#${color}`;
  const colorizedSvg = svgSrc.replaceAll('currentColor', hexColor);
  return colorizedSvg;
}


export async function getTsDefinitionForItem(info: TypeGenItemInfo, indentLevel = 0) {
  const i = _.times(indentLevel, () => '  ').join('');
  const itemSrc = [];

  // TODO: also will need to figure out how we deal with null values
  // since we might need something like `key: string | null` rather than `key?: string`

  const jsDocLines = [];

  jsDocLines.push(`**${info.key}**${info.isSensitive ? ' 🔐 _sensitive_' : ''}`);

  if (info.description) jsDocLines.push(...info.description.split('\n'));
  // type-description?

  const iconName = info.icon;
  if (iconName) {
    // TODO: pass through custom icon color? (already exists on fetchIconSvg)
    const iconSvg = await fetchIconSvg(iconName);
    if (iconSvg) jsDocLines.push(`![icon](data:image/svg+xml;utf-8,${encodeURIComponent(iconSvg)}) `);
  }

  const docsLinks = info.docsLinks;
  if (docsLinks.length) {
    jsDocLines.push('');
    docsLinks.forEach((docsEntry) => {
      // see https://jsdoc.app/tags-see for format info
      const docsLink = _.compact([docsEntry.url, docsEntry.description]).join(' | ');
      jsDocLines.push(`📚 {@link ${docsLink}}`);
    });
  }

  // more ideas:
  // - we have an `exampleValue` property we could include
  // - there's also a `@example` jsdoc directive which is meant to show a code example
  // - could add info about the original source of an item if it has been picked / imported
  // - could include additional text about type settings / validations

  if (jsDocLines.length === 1) {
    itemSrc.push(`/** ${jsDocLines[0]} */`);
  } else if (jsDocLines.length > 1) {
    itemSrc.push(...[
      '/**',
      // extra 2 trailing spaces are needed to make line breaks visible
      ..._.flatMap(jsDocLines, (line) => [` * ${line}  `]),
      ' */',
    ]);
  }

  // TODO: logic should probably be within the Item class(es) and we still need to figure out how to identify these types...
  const dataType = info.dataType;
  const dataTypeName = dataType?.name;

  let itemTsType = 'string';
  if (dataType) {
    if (dataTypeName === 'number' || dataTypeName === 'port') {
      itemTsType = 'number';
    } else if (dataTypeName === 'boolean') {
      itemTsType = 'boolean';
    } else if (dataTypeName === 'simple-object') {
      itemTsType = 'Record<string, any>';
    } else if (dataTypeName === 'enum') {
      // enums have several different formats we need to handle
      const rawEnumOptions = (dataType._rawDef as any)._rawEnumOptions;
      let enumOptions = [] as Array<any>;
      enumOptions = rawEnumOptions;

      // TODO: we'll likely add other formats later where enum options can have attached descriptions

      if (!enumOptions.length) {
        itemTsType = 'never'; // should it be any instead?
      } else {
        // we could spit out descriptions in comments here, although currently it does nothing
        // see https://github.com/microsoft/TypeScript/issues/38106
        itemTsType = _.map(enumOptions, JSON.stringify).join(' | ');
      }
    }
    // TODO: eventually handle objects, arrays, dictionaries
  }

  const isRequired = info.isRequired && !info.isRequiredDynamic;
  itemSrc.push(`${info.key}${isRequired ? '' : '?'}: ${itemTsType};`);
  itemSrc.push('');
  return _.map(itemSrc, (line) => `${i}${line}`);
}

export async function generateTsTypesSrc(items: Array<TypeGenItemInfo>) {
  // TODO: first check if schema is valid - we dont care if values are invalid

  const tsSrc = [
    AUTOGENERATED_FILE_BANNER,
    // might want to add some options to let users inject this, or somehow detect eslint, but fine for now
    '/* eslint-disable */',
    'export type CoercedEnvSchema = {',
  ];

  const exposedKeys: Array<string> = [];
  const exposedNonSensitiveKeys: Array<string> = [];
  for (const info of items) {
    // generate the TS type for the item in the full schema
    tsSrc.push(...await getTsDefinitionForItem(info, 1));

    // TODO: we will want the ability to keep some items internal and not exposed in the schema
    exposedKeys.push(info.key);
    if (!info.isSensitive) exposedNonSensitiveKeys.push(info.key);
  }

  tsSrc.push('};\n');

  tsSrc.push(`
declare module 'varlock/env' {
  export interface TypedEnvSchema extends Readonly<CoercedEnvSchema> {}
  export interface PublicTypedEnvSchema extends Readonly<Pick<CoercedEnvSchema, '${exposedNonSensitiveKeys.join("' | '")}'>> {}
}
`);

  // add types for process.env too
  // remap types for process.env
  // - enums - stay string unions if all options are strings
  // - boolean -> 'true' | 'false'
  // - everything else -> string
  tsSrc.push(`
export type EnvSchemaAsStrings = {
  [Property in keyof CoercedEnvSchema]:
    CoercedEnvSchema[Property] extends string ? CoercedEnvSchema[Property]
      : (CoercedEnvSchema[Property] extends boolean ? ('true' | 'false') : string)
};
`);

  // TODO: allow user to pass in options to control this?
  // although because we add the @generateTypes decorator an init time
  // we may need our integrations to specify what settings they prefer
  const importMetaEnvTypes = true;
  const processEnvTypes = true;

  const IMPORT_META_AUGMENTATION = `
  // add types for global import.meta.env
  interface ImportMetaEnv extends EnvSchemaAsStrings {}
  interface ImportMeta {
    readonly env: ImportMetaEnv;
  }`;
  const PROCESS_ENV_AUGMENTATION = `
  // add types for global process.env
  namespace NodeJS {
    interface ProcessEnv extends EnvSchemaAsStrings {}
  }`;

  // TODO: should add an option to enable/disable
  tsSrc.push(...[
    'declare global {',
    importMetaEnvTypes && IMPORT_META_AUGMENTATION,
    processEnvTypes && PROCESS_ENV_AUGMENTATION,
    '}',
  ].filter(Boolean));

  return tsSrc.join('\n');
}

function getTypeGenItems(graph: EnvGraph) {
  const items: Array<Promise<TypeGenItemInfo>> = [];
  for (const itemKey of graph.sortedConfigKeys) {
    const configItem = graph.configSchema[itemKey];
    if (!configItem.defsForTypeGeneration.length) continue;
    items.push(configItem.getTypeGenInfo());
  }

  return Promise.all(items);
}

function toPascalCaseIdentifier(key: string) {
  const parts = key.split(/[^A-Za-z0-9]+/).filter(Boolean);
  const transformed = parts.map((part) => {
    if (/^\d+$/.test(part)) return part;

    const normalized = `${part[0].toUpperCase()}${part.slice(1).toLowerCase()}`;
    return normalized;
  }).join('');

  let identifier = transformed || 'Value';
  if (/^\d/.test(identifier)) identifier = `_${identifier}`;
  if (CSHARP_RESERVED_WORDS.has(identifier)) identifier = `${identifier}Value`;
  return identifier;
}

function escapeXmlDoc(text: string) {
  return text
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;');
}

function getEnumOptions(info: TypeGenItemInfo) {
  if (info.dataType?.name !== 'enum') return [] as Array<string>;

  const rawEnumOptions = (info.dataType._rawDef as any)._rawEnumOptions;
  if (!_.isArray(rawEnumOptions)) return [];

  return _.map(rawEnumOptions, (option) => String(option));
}

function getCsTypeForItem(info: TypeGenItemInfo) {
  const isRequired = info.isRequired && !info.isRequiredDynamic;
  const dataTypeName = info.dataType?.name;

  if (dataTypeName === 'port') {
    return { typeName: isRequired ? 'int' : 'int?', initializer: '' };
  }
  if (dataTypeName === 'number') {
    return { typeName: isRequired ? 'double' : 'double?', initializer: '' };
  }
  if (dataTypeName === 'boolean') {
    return { typeName: isRequired ? 'bool' : 'bool?', initializer: '' };
  }
  if (dataTypeName === 'simple-object') {
    return {
      typeName: 'global::System.Collections.Generic.Dictionary<string, object>',
      initializer: isRequired ? ' = new global::System.Collections.Generic.Dictionary<string, object>();' : '',
    };
  }

  return { typeName: 'string', initializer: ' = string.Empty;' };
}

type CsTypeGenMemberInfo = {
  info: TypeGenItemInfo;
  propertyName: string;
};

type TypeGenerationOptions = {
  namespace?: unknown;
  typeName?: unknown;
};

type CsTypeGenerationOptions = {
  namespaceName: string;
  typeName: string;
  metadataTypeName: string;
};

function getCsTypeGenMembers(items: Array<TypeGenItemInfo>) {
  const usedNames = new Map<string, number>();

  return items.map((info) => {
    const baseName = toPascalCaseIdentifier(info.key);
    const existingCount = usedNames.get(baseName) ?? 0;
    usedNames.set(baseName, existingCount + 1);

    return {
      info,
      propertyName: existingCount === 0 ? baseName : `${baseName}${existingCount + 1}`,
    } satisfies CsTypeGenMemberInfo;
  });
}

function getCsDocLines(info: TypeGenItemInfo) {
  const lines = [`Original key: ${info.key}.`];

  if (info.isSensitive) lines.push('Sensitive.');

  const enumOptions = getEnumOptions(info);
  if (enumOptions.length) lines.push(`Allowed values: ${enumOptions.join(', ')}.`);

  if (info.description) lines.push(...info.description.split('\n'));
  return lines;
}

function isValidCsIdentifier(identifier: string) {
  return /^[A-Za-z_][A-Za-z0-9_]*$/.test(identifier);
}

function resolveCsTypeGenerationOptions(options?: TypeGenerationOptions): CsTypeGenerationOptions {
  const namespaceName = options?.namespace === undefined ? 'Varlock.Generated' : options.namespace;
  const typeName = options?.typeName === undefined ? 'VarlockConfig' : options.typeName;

  if (!_.isString(namespaceName) || namespaceName.length === 0) {
    throw new Error('@generateTypes(lang=cs) - `namespace` must be a non-empty string');
  }
  if (!namespaceName.split('.').every((segment) => segment.length > 0 && isValidCsIdentifier(segment))) {
    throw new Error('@generateTypes(lang=cs) - `namespace` must be a dot-separated list of valid C# identifiers');
  }

  if (!_.isString(typeName) || typeName.length === 0) {
    throw new Error('@generateTypes(lang=cs) - `typeName` must be a non-empty string');
  }
  if (!isValidCsIdentifier(typeName)) {
    throw new Error('@generateTypes(lang=cs) - `typeName` must be a valid C# identifier');
  }

  return {
    namespaceName,
    typeName,
    metadataTypeName: `${typeName}Metadata`,
  };
}

export async function generateCsTypesSrc(items: Array<TypeGenItemInfo>, options?: TypeGenerationOptions) {
  const members = getCsTypeGenMembers(items);
  const csOptions = resolveCsTypeGenerationOptions(options);

  const csSrc = [
    AUTOGENERATED_CSHARP_FILE_BANNER,
    '',
    `namespace ${csOptions.namespaceName}`,
    '{',
    `  public sealed partial class ${csOptions.typeName}`,
    '  {',
  ];

  for (const member of members) {
    const docLines = getCsDocLines(member.info);
    for (const docLine of docLines) {
      csSrc.push(`    /// <summary>${escapeXmlDoc(docLine)}</summary>`);
    }

    const { typeName, initializer } = getCsTypeForItem(member.info);
    csSrc.push(`    public ${typeName} ${member.propertyName} { get; set; }${initializer}`);
    csSrc.push('');
  }

  csSrc.push('  }');
  csSrc.push('');
  csSrc.push(`  public static class ${csOptions.metadataTypeName}`);
  csSrc.push('  {');
  csSrc.push('    public sealed class PropertyBinding');
  csSrc.push('    {');
  csSrc.push('      public PropertyBinding(string key, string propertyName, bool isRequired, bool isSensitive)');
  csSrc.push('      {');
  csSrc.push('        Key = key;');
  csSrc.push('        PropertyName = propertyName;');
  csSrc.push('        IsRequired = isRequired;');
  csSrc.push('        IsSensitive = isSensitive;');
  csSrc.push('      }');
  csSrc.push('');
  csSrc.push('      public string Key { get; }');
  csSrc.push('');
  csSrc.push('      public string PropertyName { get; }');
  csSrc.push('');
  csSrc.push('      public bool IsRequired { get; }');
  csSrc.push('');
  csSrc.push('      public bool IsSensitive { get; }');
  csSrc.push('    }');
  csSrc.push('');
  csSrc.push('    public static global::System.Collections.Generic.IReadOnlyList<PropertyBinding> PropertyBindings { get; } = new PropertyBinding[]');
  csSrc.push('    {');

  for (const member of members) {
    const isRequired = member.info.isRequired && !member.info.isRequiredDynamic;
    csSrc.push(`      new PropertyBinding("${member.info.key}", "${member.propertyName}", ${isRequired}, ${member.info.isSensitive}),`);
  }

  csSrc.push('    };');
  csSrc.push('');
  csSrc.push('    public static global::System.Collections.Generic.IReadOnlyDictionary<string, string> PropertyKeys { get; } =');
  csSrc.push('      new global::System.Collections.Generic.Dictionary<string, string>(global::System.StringComparer.Ordinal)');
  csSrc.push('      {');

  for (const member of members) {
    csSrc.push(`        ["${member.propertyName}"] = "${member.info.key}",`);
  }

  csSrc.push('      };');
  csSrc.push('');
  csSrc.push('    public static global::System.Collections.Generic.IReadOnlyList<string> SensitiveKeys { get; } = new string[]');
  csSrc.push('    {');

  for (const member of members.filter(({ info }) => info.isSensitive)) {
    csSrc.push(`      "${member.info.key}",`);
  }

  csSrc.push('    };');
  csSrc.push('  }');
  csSrc.push('}');

  return csSrc.join('\n');
}

export async function generateTypes(
  graph: EnvGraph,
  lang: string,
  typesPath: string,
  options?: TypeGenerationOptions,
) {
  const items = await getTypeGenItems(graph);

  if (lang === 'ts') {
    const tsSrc = await generateTsTypesSrc(items);
    await fs.promises.writeFile(typesPath, tsSrc, 'utf-8');
    return;
  }

  if (lang === 'cs') {
    const csSrc = await generateCsTypesSrc(items, options);
    await fs.promises.writeFile(typesPath, csSrc, 'utf-8');
    return;
  }

  throw new Error(`Unsupported @generateTypes lang: ${lang}`);
}
